POST http://localhost:3000/api/heroes HTTP/1.1
Content-Type: application/json

{
    "nick": "Spider-Man",
    "realName": "Peter Parker",
    "originDescription": "Spider-Man gets his superhuman spider-powers and abilities after being bitten by a radioactive spider; these include superhuman strength, speed, agility, jump, reflexes, stamina, durability, coordination and balance, clinging to surfaces and ceilings like a spider, and detecting danger with his precognition ability called \"spider-sense.\" He also builds wrist-mounted \"web-shooter\" devices that shoot artificial spider-webs of his own design that were used for fighting his enemies and web-swinging across the city. Peter Parker originally used his powers for his own personal gain, but after his Uncle Ben was killed by a thief that Peter didn't stop, Peter begins to use his spider-powers to fight crime by becoming the superhero known as Spider-Man.",
    "cathPhrase": "My spider sence is thingling"
}